"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.usersRoutes = void 0;
const express_1 = require("express");
const createUser_controller_1 = require("./controllers/createUser.controller");
const ensureAuthenticated_1 = require("../../shared/middlewares/ensureAuthenticated");
const ensureAdmin_1 = require("../../shared/middlewares/ensureAdmin");
const listUsers_controller_1 = require("./controllers/listUsers.controller");
const deleteUsers_controller_1 = require("./controllers/deleteUsers.controller");
const getUser_controller_1 = require("./controllers/getUser.controller");
const routes = (0, express_1.Router)();
exports.usersRoutes = routes;
routes.post("/", ensureAuthenticated_1.ensureAuthenticated, ensureAdmin_1.ensureAdmin, new createUser_controller_1.CreateUserController().handle);
routes.get("/:id", new getUser_controller_1.GetUserController().handle);
routes.get("/", ensureAuthenticated_1.ensureAuthenticated, ensureAdmin_1.ensureAdmin, new listUsers_controller_1.ListUsersController().handle);
routes.put("/desactive/:id", ensureAuthenticated_1.ensureAuthenticated, ensureAdmin_1.ensureAdmin, new deleteUsers_controller_1.DesactiveUsersController().handle);
routes.put("/active/:id", ensureAuthenticated_1.ensureAuthenticated, ensureAdmin_1.ensureAdmin, new deleteUsers_controller_1.ActiveUsersController().handle);
