"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.productsRoutes = void 0;
const express_1 = require("express");
const ensureAuthenticated_1 = require("../../shared/middlewares/ensureAuthenticated");
const createProductsCategories_controller_1 = require("./controllers/products-category/createProductsCategories.controller");
const listProductsCategories_controller_1 = require("./controllers/products-category/listProductsCategories.controller");
const deleteProductsCategories_controller_1 = require("./controllers/products-category/deleteProductsCategories.controller");
const editProductsCategories_controller_1 = require("./controllers/products-category/editProductsCategories.controller");
const editProductsUnits_controller_1 = require("./controllers/products-units/editProductsUnits.controller");
const deleteProductsUnits_controller_1 = require("./controllers/products-units/deleteProductsUnits.controller");
const listProductsUnits_controller_1 = require("./controllers/products-units/listProductsUnits.controller");
const createProductsUnits_controller_1 = require("./controllers/products-units/createProductsUnits.controller");
const createProducts_controller_1 = require("./controllers/products/createProducts.controller");
const listProducts_controller_1 = require("./controllers/products/listProducts.controller");
const editProducts_controller_1 = require("./controllers/products/editProducts.controller");
const deleteProducts_controller_1 = require("./controllers/products/deleteProducts.controller");
const listProductsSelect_controller_1 = require("./controllers/products/listProductsSelect.controller");
const routes = (0, express_1.Router)();
exports.productsRoutes = routes;
routes.post("/", ensureAuthenticated_1.ensureAuthenticated, new createProducts_controller_1.CreateProductsController().handle);
routes.get("/", ensureAuthenticated_1.ensureAuthenticated, new listProductsSelect_controller_1.ListProductsController().handle);
routes.put("/:id", ensureAuthenticated_1.ensureAuthenticated, new editProducts_controller_1.EditProductsController().handle);
routes.delete("/:id", ensureAuthenticated_1.ensureAuthenticated, new deleteProducts_controller_1.DeleteProductsController().handle);
routes.post("/products-categories", ensureAuthenticated_1.ensureAuthenticated, new createProductsCategories_controller_1.CreateProductsCategoriesController().handle);
routes.get("/products-categories", ensureAuthenticated_1.ensureAuthenticated, new listProductsCategories_controller_1.ListCategoriesController().handle);
routes.delete("/products-categories/:id", ensureAuthenticated_1.ensureAuthenticated, new deleteProductsCategories_controller_1.DeleteCategoriesController().handle);
routes.put("/products-categories/:id", ensureAuthenticated_1.ensureAuthenticated, new editProductsCategories_controller_1.EditCategoriesController().handle);
routes.post("/products-units", ensureAuthenticated_1.ensureAuthenticated, new createProductsUnits_controller_1.CreateProductsUnitsController().handle);
routes.get("/products-units", ensureAuthenticated_1.ensureAuthenticated, new listProductsUnits_controller_1.ListUnitsController().handle);
routes.delete("/products-units/:id", ensureAuthenticated_1.ensureAuthenticated, new deleteProductsUnits_controller_1.DeleteUnitsController().handle);
routes.put("/products-units/:id", ensureAuthenticated_1.ensureAuthenticated, new editProductsUnits_controller_1.EditUnitsController().handle);
routes.get('/select', new listProducts_controller_1.ListProductSelectController().handle);
